package:
  name: e211_lib
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../

build:
  noarch: python
  number: 0
  
    
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:

  build:
    - python=3.8
    - numpy>1.21
  
  host:
    - python=3.8
    - numpy>1.21

  run:
    - python=3.8
    - numpy>1.21
    - pandas>1.3
    - scipy>1.7
    - pillow>8.3
    - arrow


test:
  imports:
    - e211_lib

about:
  home: https://github.com/phaustin/e211_lib
  license: LICENSE.txt
  license_family: BSD

  summary: 'EOSC 211 utilities'

extra:
  recipe-maintainers:
    - phaustin
